name: Go
on: [pull_request]
jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Test
      run: make test
  build-win:
    name: Build on Windows
    runs-on: windows-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Test
      run: 	go test -timeout 10s -cover ./...

